[project]
authors = ["Laisha Wadhwa"]
entry = "main.sw"
license = "Apache-2.0"
name = "token_contract_src20"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.5.0" }
